### ISSUE TITLE
scims not sorted by time run?

### ISSUE THREAD

**Issue by npfoss** [battlecode/battlecode20#282] opened 2020-01-13 03:37 UTC
> this is just a guess, but I think if you manually accept a scrimmage request, the game gets inserted into your list of scrimmages at a position corresponding to the timestamp when request was created (which may be really far down in your list of scrimmages), when it should probably use the timestamp when the request was accepted (which would make it appear at the top like it should)

**Comment by j-mao** [comment] 2020-01-13 03:54
Duplicate of #183

**Closed by j-mao** 2020-01-13 03:54 UTC
Labels: duplicate, frontend
